# The name of this app. Must be unique within a project.
name: devis-rapide-back

type: 'java:21'

disk: 2048

hooks:
    build: 
      ./gradlew clean build --info

web:
  commands: 
    start: 
      java -jar build/libs/devis-rapide-0.0.1-SNAPSHOT.jar --server.port=$PORT

variables:
  env:
    MAIL_HOST: "smtp.example.com"
    MAIL_PORT: "587"
    MAIL_USER: "user@example.com"
    MAIL_PASSWORD: "password"
    SPRING_DATASOURCE_USERNAME: "sd_username_value"
    DISCORD_WEBHOOK: "fsasfdsaf"
    SPRING_SECURITY_USER_PASSWORD: "password"
    SPRING_DATASOURCE_PASSWORD: "sd_password_value"
    SPRING_AI_OPENAI_API_KEY: "Aasfdafd"
    SPRING_SECURITY_USER_NAME: "user"
    APP_URL: "http://localhost:4000"
    DISCORD_QUOTE_ENGINE_TOKEN: "asdfasdfad"

environments:
  test:
    variables:
      env:
        MAIL_HOST: "smtp.example.com"
        MAIL_PORT: "587"
        MAIL_USER: "user@example.com"
        MAIL_PASSWORD: "password"
        SPRING_DATASOURCE_USERNAME: "sd_username_value"
        DISCORD_WEBHOOK: "fsasfdsaf"
        SPRING_SECURITY_USER_PASSWORD: "password"
        SPRING_DATASOURCE_PASSWORD: "sd_password_value"
        SPRING_AI_OPENAI_API_KEY: "Aasfdafd"
        SPRING_SECURITY_USER_NAME: "user"
        APP_URL: "http://localhost:4000"