# The name of this app. Must be unique within a project.
name: devis-rapide-back

type: 'java:21'

disk: 2048

hooks:
    build: 
      ./gradlew clean build

web:
  commands: 
    start: 
      java -jar build/libs/devis-rapide-0.0.1-SNAPSHOT.jar --server.port=$PORT